#define MAXSTRINGLENGTH 420
#define YES {1}
#define NO {0}
#define NUMALIENS 8

struct alienQ {
  char question[MAXSTRINGLENGTH];
  byte answer[1];
};

const struct alienQ myAliens[NUMALIENS] PROGMEM = {{"DID VOSTOK 1 COMPLETE A \nFULL EARTH ORBIT?", YES}, 
{"DOES JUPITER HAVE MORE \nTHAN 20 MOONS?", YES},
{"THE FORCE WAS MODELLED \nAFTER THE CONCEPT OF \n'CHI', RIGHT?", NO},
{"DOESN'T URANUS SPIN \nBACKWARDS?", NO},
{"ISN'T MARS THE CLOSEST \nPLANET TO EARTH?", NO},
{"DOES - TIE - STAND FOR \n'THE IMPERIAL ENGINE'?", NO},
{"WAS THE SUN BORN MORE \nTHAN 4 BILLION YEARS \nAGO?", YES },
{"MARTIN SCORSESE HELPED \nEDIT THE OPENING CRAWL OF \nSTAR WARS, RIGHT?", NO}
};

